FROM python:slim
WORKDIR /sloshzero-server
COPY requirements.server.txt
RUN pip install --no-cache-dir -r requirements.server.txt
COPY . .
EXPOSE 5000
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "${FASTAPI_PORT}"]
