FROM python:slim
WORKDIR /app
COPY requirements.server.txt /app/
RUN pip install --no-cache-dir -r requirements.server.txt
COPY src/ /app/src/
EXPOSE 5000
CMD ["uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "${FASTAPI_PORT}"]
